name: Build & Publish to gh-pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci || npm i

      - name: Build site
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }} # optional if using refresh flow
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }} # optional
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}             # optional
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}       # optional
          DROPBOX_SHARED_URL: ${{ secrets.DROPBOX_SHARED_URL }}       # required
          GMAPS_API_KEY: ${{ secrets.GMAPS_API_KEY }}                 # required
          ENABLE_NOMINATIM: "0"   # set to "1" to try filename-based geocoding
        run: npm run build

      - name: Publish site/ to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
